######################
# 2 - logit cubic
#
# Fit logit cubic to eBird data to get half-max parameter (bird arrival) for each species-cell-year
#
# Formerly NA_birdPhen1.R
######################

# Loads the eBird dataset generated by Ebird_import.R, then uses Stan via the package
# rstanarm to fit a logit-cubic model to the reporting probability as a function of Julian Day in
# each species-cell-year that meets some data requirements. Several metrics are extracted from the
# fitted models. Most importantly, this is the derived half-max parameter, which is the Julian Day 
# when the fitted reporting probability first exceeds half of its maximum on the back-transformed
# identity scale, as well as a few convergence diagnostics. 


cy_dir <- '~/Google_Drive/R/'


# Load packages -----------------------------------------------------------

library(rstanarm)



# Set wd ------------------------------------------------------------------

setwd(paste0(cy_dir, 'Bird_Phenology/Data/'))



# import eBird species list -----------------------------------------------------

species_list_i <- read.table('eBird_species_list.txt')
species_list <- species_list_i[,1]
nsp <- length(species_list)

years <- 2002:2016
nyr <- length(years)



# import processed data ---------------------------------------------------


#import pdata
pdata <- readRDS('ebird_NA_phen_proc.rds')
cells <- readRDS('ebird_NA_phen_proc_cells.rds')
ncel <- length(cells)



# Create newdata ---------------------------------------------------


Mu.day <- mean(as.numeric(as.character(pdata$DAY)))
sd.day <- sd(as.numeric(as.character(pdata$DAY)))

predictDays = (c(1:200) - Mu.day)/sd.day
newdata <- data.frame(sjday = predictDays, sjday2 = predictDays^2, sjday3 = predictDays^3, shr = 1)

fit_diag <- halfmax_matrix_list <- list()



# fit logit cubic ---------------------------------------------------------

#number of iterations each model should be run
ITER = 2500


#loop through each species, year, cell and extract half-max parameter
for(i in 1:nsp)
{
  #i <- 1
  fit_diag[[i]] <- halfmax_matrix_list[[i]] <- list()
  sdata <- pdata[,c("YEAR","DAY","sjday","sjday2","sjday3","shr","cell6",paste0(species_list[i]))]
  names(sdata)[8] <- "detect"
  
  for(j in 1:nyr)
  {
    #j <- 1
    halfmax_matrix_list[[i]][[j]] <- matrix(data = NA, nrow = ncel, ncol = ITER*2)
    fit_diag[[i]][[j]] <- list()
    ysdata <- sdata[which(sdata$YEAR == years[j]), ]
    
    for(k in 1:ncel)
    {
      #k <- 1
      print(paste(i,j,k))
      fit_diag[[i]][[j]][[k]] <- list(maxRhat = NA, mineffsSize = NA)
      cysdata <- ysdata[which(ysdata$cell6 == cells[k]), ]
      n1 <- sum(cysdata$detect)
      n0 <- sum(cysdata$detect == 0)
      #number of detections that came before jday 60
      n1W <- sum(cysdata$detect * as.numeric(cysdata$DAY < 60))
      
      if(n1 > 29 & n1W < (n1/50) & n0 > 29)
      {
        fit2 <- stan_glm(detect ~ sjday + sjday2 + sjday3 + shr, 
                         data = cysdata, 
                         family = binomial(link = "logit"), 
                         algorithm = 'sampling', 
                         iter = ITER, 
                         cores = 4)
        
        dfit <- posterior_linpred(fit2, newdata = newdata, transform = T)
        halfmax_fit <- rep(NA, ITER*2)
        
        for(L in 1:ITER*2)
        {
          #L <- 1
          rowL <- as.vector(dfit[L,])
          halfmax_fit[L] <- min(which(rowL > (max(rowL)/2)))
        }
        
        ########################
        #PLOT MODEL FIT AND DATA
        
        #summary(fit2)
        
        setwd(paste0(cy_dir, 'Bird_Phenology/Results/Plots'))
        
        mn_dfit <- apply(dfit, 2, mean)
        LCI_dfit <- apply(dfit, 2, function(x) quantile(x, probs = 0.025))
        UCI_dfit <- apply(dfit, 2, function(x) quantile(x, probs = 0.975))
        
        mn_hm <- mean(halfmax_fit)
        LCI_hm <- quantile(halfmax_fit, probs = 0.025)
        UCI_hm <- quantile(halfmax_fit, probs = 0.975)
        
        pdf(paste0(species_list[i], '_', years[j], '_', cells[k], '.pdf'))
        plot(UCI_dfit, type = 'l', col = 'red', lty = 2, lwd = 2, 
             ylim = c(0,1), main = paste0(species_list[i], ' - ', years[j], ' - ', cells[k]))
        lines(LCI_dfit, col = 'red', lty = 2, lwd = 2)
        lines(mn_dfit, lwd = 2)
        points(cysdata$DAY, cysdata$detect, col = rgb(0,0,0,0.25))
        abline(v = mn_hm, col = rgb(0,0,1,0.5), lwd = 2)
        abline(v = LCI_hm, col = rgb(0,0,1,0.5), lwd = 2, lty = 2)
        abline(v = UCI_hm, col = rgb(0,0,1,0.5), lwd = 2, lty = 2)
        legend('topleft',
               legend = c('Cubic fit', 'CI fit', 'Half max', 'CI HM'),
               col = c('black', 'red', rgb(0,0,1,0.5), rgb(0,0,1,0.5)),
               lty = c(1,2,1,2), lwd = c(2,2,2,2), cex = 1.3)
        dev.off()
        ########################
        
        halfmax_matrix_list[[i]][[j]][k,] <- halfmax_fit
        fit_diag[[i]][[j]][[k]]$maxRhat <- max(summary(fit2)[, "Rhat"])
        fit_diag[[i]][[j]][[k]]$mineffsSize <- min(summary(fit2)[, "n_eff"])
      }
    }
  }
}



#save to rds object
setwd(paste0(cy_dir, '/Bird_Phenology/Data/Processed/'))

saveRDS(halfmax_matrix_list, file="halfmax_matrix_list.rds")
saveRDS(fit_diag, file="halfmax_fit_diag.rds")

