######################
# 2 - logit cubic
#
# Fit logit cubic to eBird data to get half-max parameter (bird arrival) for each species-cell-year
#
# Species name should be given as an arg to this script. The logit cubic will then be fit to that species only.
# Runtime: Each species anywhere from 10 min to ~7 days on Xanadu at 2000 iterations - neff > 500
# RAM usage: < 6 GB in general
#
# Formerly NA_birdPhen1.R
######################  

# Loads the eBird dataset generated by Ebird_import.R, then uses Stan via the package
# rstanarm to fit a logit-cubic model to the reporting probability as a function of Julian Day in
# each species-cell-year that meets some data requirements. Several metrics are extracted from the
# fitted models. Most importantly, this is the derived half-max parameter, which is the Julian Day 
# when the fitted reporting probability first exceeds half of its maximum on the back-transformed
# identity scale, as well as a few convergence diagnostics. 


# top-level dir -----------------------------------------------------------

#desktop/laptop
#dir <- '~/Google_Drive/R/'

#Xanadu
dir <- '/UCHC/LABS/Tingley/phenomismatch/'


# db query dir ------------------------------------------------------------

db_dir <- 'db_query_2018-10-15'

RUN_DATE <- '2019-01-16'



# model settings ----------------------------------------------------------

#number of iterations each model should be run
ITER <- 2500
#ITER <- 10
CHAINS <- 4



# runtime -----------------------------------------------------------------

tt <- proc.time()



# Load packages -----------------------------------------------------------

library(rstanarm)
library(dplyr)


# Set wd ------------------------------------------------------------------

setwd(paste0(dir, 'Bird_Phenology/Data/'))



# Get args fed to script --------------------------------------------------

args <- commandArgs(trailingOnly = TRUE)
#args <- 'Empidonax_virescens'


# import processed data ---------------------------------------------------

setwd(paste0(dir, 'Bird_Phenology/Data/Processed/', db_dir))

#import data for species
spdata <- readRDS(paste0('ebird_NA_phen_proc_', args, '.rds'))

cells <- unique(spdata$cell6)
ncel <- length(cells)

years <- min(spdata$year):max(spdata$year)
nyr <- length(years)



# Create newdata ---------------------------------------------------

#calculate polynomial, then center data
predictDays <- scale(c(1:200), scale = FALSE)
predictDays2 <- scale(c(1:200)^2, scale = FALSE)
predictDays3 <- scale(c(1:200)^3, scale = FALSE)


newdata <- data.frame(sjday = predictDays, sjday2 = predictDays2, sjday3 = predictDays3, shr = 0)


# fit logit cubic ---------------------------------------------------------

t_mat <- matrix(data = NA, nrow = ncel*nyr, ncol = ((ITER/2)*CHAINS))
colnames(t_mat) <- paste0('iter_', 1:((ITER/2)*CHAINS))
halfmax_df <- data.frame(species = args, 
                         year = rep(years, each = ncel), 
                         cell = rep(cells, nyr), 
                         max_Rhat = NA,
                         min_neff = NA,
                         n1 = NA,
                         n1W = NA,
                         n0 = NA,
                         n0i = NA,
                         njd1 = NA,
                         njd0 = NA,
                         njd0i = NA,
                         t_mat)


#create dir for figs if doesn't exist
ifelse(!dir.exists(paste0(dir, 'Bird_Phenology/Figures/cubic_halfmax/arrival_', RUN_DATE)), 
       dir.create(paste0(dir, 'Bird_Phenology/Figures/cubic_halfmax/arrival_', RUN_DATE)), 
       FALSE)

setwd(paste0(dir, 'Bird_Phenology/Figures/cubic_halfmax/arrival_', RUN_DATE))


#loop through each species, year, cell and extract half-max parameter
counter <- 1
for (j in 1:nyr)
{
  #j <- 1
  yspdata <- spdata[which(spdata$year == years[j]), ]
  
  for (k in 1:ncel)
  {
    #k <- 8
    print(paste0('species: ', args, ', year: ', j, ', cell: ', k))
    
    cyspdata <- yspdata[which(yspdata$cell6 == cells[k]), ]
    
    #number of surveys where species was detected
    n1 <- sum(cyspdata$detect)
    #number of surveys where species was not detected
    n0 <- sum(cyspdata$detect == 0)
    #number of detections that came before jday 60
    n1W <- sum(cyspdata$detect * as.numeric(cyspdata$day < 60))
    #number of unique days with detections
    njd1 <- length(unique(cyspdata$day[which(cyspdata$detect == 1)]))
    #number of unique days with non-detection
    njd0 <- length(unique(cyspdata$day[which(cyspdata$detect == 0)]))
    
    
    if (n1 > 0)
    {
      #number of unique days of non-detections before first detection
      njd0i <- length(unique(cysdata$day[which(cysdata$detect == 0 & cysdata$day < 
                                                 min(cysdata$day[which(cysdata$detect == 1)]))]))
      #number of non-detections before first detection
      n0i <- length(which(cysdata$detect == 0 & 
                            cysdata$day < min(cysdata$day[which(cysdata$detect == 1)])))
    } else {
      njd0i <- 0
      n0i <- 0
    }
    
    if (n1 > 29 & n1W < (n1/50) & n0 > 29 & njd0i > 29 & njd1 > 19)
    {
      fit2 <- rstanarm::stan_glm(detect ~ sjday + sjday2 + sjday3 + shr,
                       data = cyspdata,
                       family = binomial(link = "logit"),
                       algorithm = 'sampling',
                       iter = ITER,
                       chains = CHAINS,
                       cores = CHAINS)

      dfit <- rstanarm::posterior_linpred(fit2, newdata = newdata, transform = T)
      halfmax_fit <- rep(NA, ((ITER/2)*CHAINS))
      
      for (L in 1:((ITER/2)*CHAINS))
      {
        #L <- 1
        rowL <- as.vector(dfit[L,])
        halfmax_fit[L] <- min(which(rowL > (max(rowL)/2)))
      }
      
      ########################
      #PLOT MODEL FIT AND DATA
      
      #summary(fit2)
      mn_dfit <- apply(dfit, 2, mean)
      LCI_dfit <- apply(dfit, 2, function(x) quantile(x, probs = 0.025))
      UCI_dfit <- apply(dfit, 2, function(x) quantile(x, probs = 0.975))
      mn_hm <- mean(halfmax_fit)
      LCI_hm <- quantile(halfmax_fit, probs = 0.025)
      UCI_hm <- quantile(halfmax_fit, probs = 0.975)

      pdf(paste0(args, '_', years[j], '_', cells[k], '_arrival.pdf'))
      plot(UCI_dfit, type = 'l', col = 'red', lty = 2, lwd = 2,
           ylim = c(0, max(UCI_dfit)),
           main = paste0(args, ' - ', years[j], ' - ', cells[k]),
           xlab = 'Julian Day', ylab = 'Detection Probability')
      lines(LCI_dfit, col = 'red', lty = 2, lwd = 2)
      lines(mn_dfit, lwd = 2)
      cyspdata$detect[which(cyspdata$detect == 1)] <- max(UCI_dfit)
      points(cyspdata$day, cyspdata$detect, col = rgb(0,0,0,0.25))
      abline(v = mn_hm, col = rgb(0,0,1,0.5), lwd = 2)
      abline(v = LCI_hm, col = rgb(0,0,1,0.5), lwd = 2, lty = 2)
      abline(v = UCI_hm, col = rgb(0,0,1,0.5), lwd = 2, lty = 2)
      legend('topleft',
             legend = c('Cubic fit', 'CI fit', 'Half max', 'CI HM'),
             col = c('black', 'red', rgb(0,0,1,0.5), rgb(0,0,1,0.5)),
             lty = c(1,2,1,2), lwd = c(2,2,2,2), cex = 1.3)
      dev.off()

      ########################
      
      halfmax_df$n1[counter] <- n1
      halfmax_df$n1W[counter] <- n1W
      halfmax_df$n0[counter] <- n0
      halfmax_df$n0i[counter] <- n0i
      halfmax_df$njd1[counter] <- njd1
      halfmax_df$njd0[counter] <- njd0
      halfmax_df$njd0i[counter] <- njd0i
      
      iter_ind <- grep('iter', colnames(halfmax_df))
      halfmax_df[counter,iter_ind] <- halfmax_fit
      halfmax_df$max_Rhat[counter] <- round(max(summary(fit2)[, "Rhat"]), 2)
      halfmax_df$min_neff[counter] <- min(summary(fit2)[, "n_eff"])
    }
    counter <- counter + 1
  } #k
} #j


#save to rds object
setwd(paste0(dir, '/Bird_Phenology/Data/Processed/halfmax_species_', RUN_DATE))
saveRDS(halfmax_df, file = paste0('halfmax_df_arrival_', args, '.rds'))



# runtime -----------------------------------------------------------------

time <- proc.time() - tt
rtime <- round(time[3]/60, 2)
paste0('Runtime (minutes): ', rtime)


print('I completed!')
